# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.yaml:
  security-defined:
    - '#/paths/~1posts/get'
    - '#/paths/~1posts/post'
    - '#/paths/~1posts~1{id}/get'
    - '#/paths/~1posts~1{id}/put'
    - '#/paths/~1posts~1{id}/delete'
